### PR TITLE
Prepare for deployment

### LINKED ISSUE #9: Create npm package
Using `npm link` is only a good solution during development. I would like to include this as a dev dependency in my `package.json` so everybody in the team uses the lint by default.

It would be nice to add the project to a CI and configure it to do automatic deployments when a new tag is added.

### PR DESCRIPTION
**Pull request by Istar-Eldritch**
Resolves #9 

Adds `.npmignore` so only the following files go to the deployment package:
 - `LICENSE`
 - `README`
 - `package.json`
 - `.build/src/`

I had to add typescript and tslint to devDependencies to allow the tsc compilation.

I removed the `lib` folder and left only the `.build` one, also modified the package.json to point to it. If you think lib is better we can change the output folder to lib again. We come back to a single folder for the artifacts 😄

@angelozerr If you don't have an npm account is time to create one. You can do `npm login` once you have one to create an access token, you'll have to add it to the CI to allow the deployments.

This token is added to your `~/.npmrc` file if you use linux / macosx. I'm not sure where this file is in win. 

Once you have this use the `travis-cli`: `travis setup npm` follow the steps, add the token from the previous file and it will add the deployment part of the travis.yml file. Ensure you select the encrypt option during the steps so the token is not in plain text.

To finalize ensure that you have in the deployment section  `skip_cleanup: true` and `deploy: on: tags: true`

```yml
deploy:
  ...
  on:
    tags: true
  skip_cleanup: true

```

More info:
https://docs.travis-ci.com/user/deployment/npm/

### CODE REVIEW

**Comment by Istar-Eldritch** [comment]
BTW i've seen the CI is failing and I think is because is using an old version of node. Did you pick 0.10 for some specific reason? If not I would recommend moving to 6, it's the current LTS.

**Comment by angelozerr** [comment]
> I had to add typescript and tslint to devDependencies to allow the tsc compilation.

Yes sure. No dependencies are very clean.

> I removed the lib folder and left only the .build

Why don't you like `bin `name? It's like TypeScript. Angular language service uses `bundles` https://github.com/angular/angular/blob/master/packages/language-service/package.json#L5

> @angelozerr If you don't have an npm account is time to create one. 

I have an npm account since I have already published other libraries.

> Did you pick 0.10 for some specific reason?

No, please change it with your PR. Thanks.

**Comment by Istar-Eldritch** [comment]
> Why don't you like bin name? It's like TypeScript. Angular language service uses bundles

It's not that I like it or not, in fact I don't usually use .build, I usually call it `dist`. I added the preceding `.` to hide the folder in unix systems as it not a folder you use during development.

I'm open to change it to `lib` | `bin` | `dist` ... whatever you want. 

During the building process, tsc will generate the `src` and `test` folders inside the .build folder. I took it as an intermediary folder, that's the reason I called it `.build`. If you want, we can use the CI and move the `.build/src` to `bin` so the deployment package may look cleaner. 

Nevertheless, I dont think no one really looks into the npm_modules folder, and if they do, I don't think they'll mind the project structure, the package.json states where the main is. If the users are interested in the source code, they will come to GitHub to check the originals, instead of the transpiled. So I don't see any reason to worry too much about where the artifacts are stored.

**Comment by angelozerr** [comment]
Thanks again @Istar-Eldritch for your clarification. I'm sorry with my lot of questions. I would like just understand your dev. Hope I don't loose your time.

Thanks again!

Next step: write more tests, because this plugins is not really robust. More I would like to study if codefix can be supported with TypeScript 2.3 without tsserver-plugins because of https://github.com/Microsoft/TypeScript/issues/13435

**Comment by angelozerr** [comment]
@Istar-Eldritch I hav etried to publish tslint-language-service but it seems that it doesn't publish `.build/src` folder althout .npmignore is just `.build/test` .

Do you think it's better it's called `.build`  with a dot? I will try with another name without dot.

Thanks for your help!

**Comment by angelozerr** [comment]
I have tried to rename .build to out but without success -( Any help are welcome to publish out folder. Thanks!

**Comment by Istar-Eldritch** [comment]
Did you manage to solve the issue? If not, I'll take a look at it Sunday. I'm in the road right now ;)

**Comment by angelozerr** [comment]
No @Istar-Eldritch I have try to publish it https://www.npmjs.com/package/tslint-language-service but it doesn't work since out folder was not published -(

Thanks for your help!

**Comment by Istar-Eldritch** [comment]
I just added a new PR #12 that should solve this issue. I'm sorry, I didn't check the deployment bundle for this PR.

**Comment by angelozerr** [comment]
Your help is very great! Thanks @Istar-Eldritch 

I'm studying how to manage codefix with TypeScript 2.2.1 without tsserver-plugins.  After that I will do the release.

**Pull request merged**
