### PR TITLE
Feature/53 always show disable rule fix

### LINKED ISSUE #53: Show the disable-next-line fix always.
Currently, the `disable-next-line` comment 'fix' shows up and works when there is another fix (eg `ordered-imports`) but not when there's no real fix provided (eg `no-implicit-dependencies`)
I suppose this is wrong, and it differs from `vscode-tslint`

### PR DESCRIPTION
**Pull request by reduckted**
Fixes #53.

These changes allow the "disable rule for the next line" fix to be shown when there are no other fixes available. 

Basically, instead of only recording a failure if it can be fixed, the failure is always recorded along with a boolean that indicates whether it can be fixed. Then, anywhere that was previously looking at the recorded failures (which were always fixable) will filter the failures so that it only uses the fixable failures. The only exception to this is when adding the "disable rule for the next line" fix. It will add the fix regardless of whether the failure is fixable.

I've also renamed any variables called `problem` to `failure` to avoid any confusion about whether it's a `tslint.Failure` or the new `Problem` interface I created, which is why there seems to be a lot of changes.

### CODE REVIEW

**Comment by angelozerr** [comment]
@egamma what do you think?

**Comment by arogg** [comment]
Thanks @reduckted for this , i am using your fix right now (regardless if its good or not, I just needed it), but if a line has 2 problems, I can't disable both problems (only the last comment goes into effect and the fix suggestion thus keeps alternating). Example: (requirePath is any)

```
// tslint:disable-next-line:variable-name
// tslint:disable-next-line:no-unsafe-any
// tslint:disable-next-line:non-literal-require
// tslint:disable-next-line:no-unsafe-any
// tslint:disable-next-line:non-literal-require
// tslint:disable-next-line:no-unsafe-any
// tslint:disable-next-line:non-literal-require
// tslint:disable-next-line:no-unsafe-any
const Plugin = require(requirePath) as RuntimePluginConstructor<PluginTypes<WebProjectType>>;
```

If this problem is yours you should fix it, otherwise great work :D

**Comment by reduckted** [comment]
Hmm, that looks like it might be a bug in TSLint. Here's the same problem using the VS Code extension instead of the language service:

disabled

Edit: Actually, it looks like it is a bug in this package (it just happens to be the same bug that the VS Code extension has), but it's an existing bug that would happen even without the changes in this PR.

**Comment by egamma** [comment]
@reduckted actually the tslint plugin and vscode-tslint share code and share this limitation, so this is not a tslint issue.

// FYI @mjbvz

**Comment by reduckted** [comment]
Closing this since TSLint has been deprecated.

**Pull request closed without merging**
