### PR TITLE
Make configFile relative to project root

### PR DESCRIPTION
**Pull request by krzkaczor**
Solves https://github.com/angelozerr/tslint-language-service/issues/55

This is a breaking change.

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @krzkaczor for your contribution! @egamma what do you think about this PR?

**Comment by egamma** [comment]
There is indeed an issue when relative paths are used in the `configFile` option. Since it is not defined what the current working directory of the language server process is. We need to specify what a relative path in the `configFile` path means and how it is resolved. Specifying that it the path is relative to the project root as is done in the PR makes sense. 

The PR always makes the path relative to the projectRoot. This should only be done when the path is indeed a relative path. If the path is an absolute path then it should not be changed.

In the documentation of the configuration options in https://github.com/angelozerr/tslint-language-service#configuration-options I suggest to change the documentation from:

>configFile - the configuration file that tslint should use instead of the default tslint.json.

to:

> configFile - the configuration file that tslint should use instead of the default tslint.json. A relative file path is resolved relative to the project root.

**Comment by krzkaczor** [comment]
@egamma agreed that note about this behavior should be specified in the readme.

>The PR always makes the path relative to the projectRoot. This should only be done when the path is indeed a relative path. If the path is an absolute path then it should not be changed.

You're right. I will take care of a case of absolute path. I will update PR later today.

**Comment by krzkaczor** [comment]
@egamma @angelozerr done.

**Comment by angelozerr** [comment]
Thanks @krzkaczor! @egamma I think we could merge this PR?

**Comment by egamma** [comment]
LGTM 👍 thanks

**Comment by angelozerr** [comment]
Thanks @krzkaczor for your contribution! Thanks @egamma for your review!

**Pull request merged**
